#!/usr/bin/env bash

mkdir -p vim/autoload
if [ ! -f vim/autoload/plug.vim ]; then
    echo "No autoload, fetching"
    iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim |`
    ni "$(@($env:XDG_DATA_HOME, $env:LOCALAPPDATA)[$null -eq $env:XDG_DATA_HOME])/nvim-data/site/autoload/plug.vim" -Force
fi
mkdir -p ~/.vim/swaps ~/.vim/backups ~/.vim/undo

