#!/usr/bin/env bash

mkdir -p vim/autoload
if [ ! -f vim/autoload/plug.vim ]; then
	echo "No autoload, fetching"
	curl -fLo vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim;
fi
mkdir -p ~/.vim/swaps ~/.vim/backups ~/.vim/undo

